name = "LiquidElectrolytes"
uuid = "5a7dfd8c-b3af-4c8d-a082-d3a774d75e72"
authors = ["JÃ¼rgen Fuhrmann <juergen-fuhrmann@web.de>"]
version = "0.0.2"

[deps]
CodeTracking = "da1fd8a2-8d9e-5ec2-8556-3022fb5608a2"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
CompositeStructs = "534720e6-2374-40c5-8712-bf9a2f1643c6"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ExtendableGrids = "cfc395e8-590f-11e8-1f13-43a2532b2fa8"
GridVisualize = "5eed8a63-0fb0-45eb-886d-8d5a387d12b8"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
VoronoiFVM = "82b139dc-5afc-11e9-35da-9b9bdfd336f3"

[compat]
CodeTracking v1.0.9
Colors v0.12.8
CompositeStructs v0.1.3
DocStringExtensions v0.8.6
ExtendableGrids v0.9.6
GridVisualize v0.5.1
NLsolve v4.5.1
Parameters v0.12.3
PhysicalConstants v0.2.1
PlutoUI v0.7.39
ProgressLogging v0.1.4
StaticArrays v1.4.4
Unitful v1.11.0
VoronoiFVM v0.16.3
